# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==29.0.0        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.2             # https://pypi.org/project/robocorp
    - pytest==8.3.3               # https://pypi.org/project/pytest
    - flake8==7.1.1               # https://pypi.org/project/flake8
    - black==24.10.0               # https://pypi.org/project/black
    - isort==5.13.2               # https://pypi.org/project/isort
    - pylint==3.3.1               # https://pypi.org/project/pylint/
    - robocorp-browser==2.3.4     # https://pypi.org/project/robocorp-browser
